skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lottery = "BkMhRmJCsnZ2bW9RkjK3mPQTEbtY6gpnX8H7AJQRrmbh"
undegen_core = "7HqLyczSoYYkru9xQ2QwiAN3kp156h2fr4z8EMeNJs3X"
undegen_protocol = "2icvBp1n9eyB9nKeC5vp6tXj6UJjZHvAJcvBiyGjqvLT"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
