import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="relative min-h-screen overflow-x-clip bg-transparent text-foreground">
      <main className="relative z-10 mx-auto max-w-3xl min-h-screen px-6 pt-28 pb-24 md:pb-16 flex flex-col gap-8">
        {/* Back Button */}
        <div>
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm text-muted hover:text-foreground transition-colors duration-200"
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <line x1="19" y1="12" x2="5" y2="12" />
              <polyline points="12 19 5 12 12 5" />
            </svg>
            Back to Home
          </Link>
        </div>

        {/* Header */}
        <div className="border-b border-border-low pb-6">
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight text-foreground">
            Terms of Service
          </h1>
          <p className="text-sm text-muted mt-2">
            Last updated: July 8, 2026
          </p>
        </div>

        {/* Content */}
        <div className="flex flex-col gap-6 text-sm text-muted leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-foreground">1. Agreement to Terms</h2>
            <p>
              By accessing or using the Undegen prediction syndicate platform, you agree to be bound by these Terms of Service. If you do not agree, you must immediately cease all access and participation.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-foreground">2. Wallet &amp; Eligibility</h2>
            <p>
              Participation in Undegen requires connecting a compatible Solana blockchain wallet. You are solely responsible for managing your private keys and securing your wallet. You must comply with all applicable local, national, and international laws regarding digital assets and predictions.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-foreground">3. Prediction Pools &amp; Yield Mechanics</h2>
            <p>
              Undegen offers prediction pools where users vote on match outcomes. The yield generated by pool assets is distributed according to consensus results. Under the &ldquo;win big or lose nothing&rdquo; system, staked principal is refundable in accordance with pool-specific lobby timelines, but you acknowledge that all smart contract interactions carry inherent blockchain-related risks.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-foreground">4. Risks &amp; Disclaimers</h2>
            <p>
              Cryptographic assets are subject to high market volatility. You understand that participation involves software protocol risks, smart contract vulnerabilities, and changes in regulatory frameworks. Undegen is provided on an &ldquo;as-is&rdquo; and &ldquo;as-available&rdquo; basis.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-foreground">5. Modifications to Service</h2>
            <p>
              We reserve the right to modify, suspend, or discontinue any aspect of the platform at any time without notice. We may update these Terms periodically, and your continued usage constitutes acceptance of any changes.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
