import React from "react";
import { Timeline, TimelineEntry } from "./Timeline";

export default function HowItWorks() {
  const steps: TimelineEntry[] = [
    {
      title: "1. Stake Stablecoins",
      content: (
        <div className="space-y-4">
          <p className="text-neutral-600 dark:text-neutral-400 text-sm md:text-base leading-relaxed">
            Lock USDC for one week to start earning daily yield. Your principal
            is never touched, ensuring zero-loss participation in prediction
            markets.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 max-w-md backdrop-blur-lg border border-border-low rounded-xl p-4">
            <div className="flex-1">
              <span className="text-xs text-neutral-400 block font-medium uppercase tracking-wider">
                You Stake
              </span>
              <span className="text-xl font-bold text-foreground">
                1,000 USDC
              </span>
            </div>
            <div className="w-px bg-border-low hidden sm:block" />
            <div className="flex-1">
              <span className="text-xs text-neutral-400 block font-medium uppercase tracking-wider">
                Weekly Yield Pool
              </span>
              <span className="text-xl font-bold text-foreground">
                +0.96 USDC / week
              </span>
            </div>
          </div>
        </div>
      ),
    },
    {
      title: "2. Vote Daily",
      content: (
        <div className="space-y-4">
          <p className="text-neutral-600 dark:text-neutral-400 text-sm md:text-base leading-relaxed">
            Every day, a new batch of high-odds predictions curated from global
            sporting fixtures appears. Browse the matches and cast your vote on
            the outcome you support.
          </p>
          <div className="border border-border-low rounded-xl p-4  max-w-md space-y-3">
            <div className="flex justify-between items-center text-xs font-semibold text-neutral-400">
              <span>BATCH #5 FIXTURE</span>
              <span className="text-amber-500 bg-amber-500/10 px-2 py-0.5 rounded-full text-[10px]">
                VOTING LIVE
              </span>
            </div>
            <div className="flex justify-between items-center">
              <span className="font-bold text-sm text-foreground">
                Argentina vs France
              </span>
              <span className="text-xs text-neutral-400">Starts in 4h</span>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              <div className="p-2.5 rounded-lg border border-primary/30  text-center">
                <span className="block text-[10px] text-neutral-400 uppercase">
                  Argentina Win
                </span>
                <span className="font-bold text-sm text-primary">
                  2.1x Odds
                </span>
              </div>
              <div className="p-2.5 rounded-lg border border-border-low text-center opacity-60">
                <span className="block text-[10px] text-neutral-400 uppercase">
                  France Win
                </span>
                <span className="font-bold text-sm text-foreground">
                  3.2x Odds
                </span>
              </div>
            </div>
          </div>
        </div>
      ),
    },
    {
      title: "3. Syndicate Predicts",
      content: (
        <div className="space-y-4">
          <p className="text-neutral-600 dark:text-neutral-400 text-sm md:text-base leading-relaxed">
            The protocol aggregates the daily interest/yield generated by the
            entire staked pool. Instead of paying interest back to individuals
            daily, it allocates this collective yield to the community's
            top-voted outcome.
          </p>
          <div className="max-w-md  border border-border-low rounded-xl p-4 space-y-4">
            <div className="flex justify-between items-center text-xs">
              <span className="text-neutral-400 font-medium">
                Yield Pool Allocation
              </span>
              <span className="font-semibold text-foreground">
                Daily Yield: 1,200 USDC
              </span>
            </div>
            <div className="space-y-2">
              <div className="flex justify-between text-xs">
                <span className="text-foreground font-semibold">
                  Argentina to win (82% votes)
                </span>
                <span className="text-neutral-400 font-medium">
                  984 USDC Allocated
                </span>
              </div>
              <div className="w-full bg-border-low h-2 rounded-full overflow-hidden">
                <div
                  className="bg-primary h-full rounded-full"
                  style={{ width: "82%" }}
                />
              </div>
            </div>
          </div>
        </div>
      ),
    },
    {
      title: "4. Earn Together",
      content: (
        <div className="space-y-4">
          <p className="text-neutral-600 dark:text-neutral-400 text-sm md:text-base leading-relaxed">
            If the community's prediction is correct, the protocol pays out
            high-multiplier rewards from the treasury, distributed
            proportionally to your pool share. If incorrect, only the day's
            yield is lost — your principal stays 100% safe.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-w-md">
            <div className="p-4 border border-foreground/20 bg-foreground/5 rounded-xl space-y-1">
              <span className="text-[10px] text-foreground font-bold uppercase tracking-wider">
                Scenario A: Win
              </span>
              <p className="text-xs text-neutral-600 dark:text-neutral-400">
                Receive yield rewards scaled up by winning fixture odds.
              </p>
              <span className="text-sm font-bold text-foreground block pt-1">
                +5.04 USDC Daily Reward
              </span>
            </div>
            <div className="p-4 border border-border-low rounded-xl space-y-1">
              <span className="text-[10px] text-neutral-400 font-bold uppercase tracking-wider">
                Scenario B: Loss
              </span>
              <p className="text-xs text-neutral-600 dark:text-neutral-400">
                Daily yield is lost, but your principal is fully returned.
              </p>
              <span className="text-sm font-bold text-foreground block pt-1">
                1,000 USDC Safe
              </span>
            </div>
          </div>
        </div>
      ),
    },
  ];

  return (
    <div className="py-6 rounded-2xl backdrop-blur-sm border border-border-low">
      <Timeline
        data={steps}
        title="How the Syndicate Works"
        description="Learn how the protocol works step-by-step, from staking stablecoins to earning rewards with the community."
      />
    </div>
  );
}
