/**
 * Solana Integration Configuration
 *
 * Smart Contract Developers: Edit these constants to point the frontend
 * to your custom RPC endpoints and tokens. Program IDs are NOT here — they
 * come straight off each program's own IDL (app/app/lib/idl/*.json,
 * regenerated by `anchor build`), so a redeploy under a new address never
 * needs a matching edit in this file.
 */
export const SOLANA_CONFIG = {
  RPC_URL: "https://api.devnet.solana.com",

  // USDC Mint Address (devnet test USDC used by undegen_core)
  USDC_MINT: "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",

  // Decimals of the deposit token (USDC uses 6)
  TOKEN_DECIMALS: 6,

  COMMITMENT: "confirmed" as const,
};
